export let AllJobs = [
  {
    id: 1,
    active: true,
    companyName: 'Coding Ninja',
    department: 'Tech',
    position: 'SDE',
    location: 'Gurgaon HR IND Remote',
    salary: '14-20 lpa',
    skills: ['ReactJS', 'NodeJS', 'JS', 'SQL', 'MongoDB', 'Express', 'AWS'],
    dueDate: '30 Aug 2023',
    numberOfOpenings: 5,
    currentApplicants: 1,
    lastPosted: ['4/12/2023', '2:32:33 AM'],
  },
  {
    id: 2,
    active: true,
    companyName: 'Go Digit',
    department: 'Tech',
    position: 'Angular Developer',
    location: 'Pune IND On-Site',
    salary: '6-10 lpa',
    skills: ['AngularJS', 'JS', 'SQL', 'MongoDB', 'Express', 'AWS'],
    dueDate: '30 Aug 2023',
    numberOfOpenings: 7,
    currentApplicants: 0,
    lastPosted: ['4/12/2023', '2:32:33 AM'],
  },
  {
    id: 3,
    active: false,
    companyName: 'Juspay',
    department: 'Tech',
    position: 'SDE',
    location: 'Banglore IND',
    salary: '20-26 lpa',
    skills: ['AngularJS', 'JS', 'SQL', 'MongoDB', 'Express', 'AWS'],
    dueDate: '30 Aug 2023',
    numberOfOpenings: 3,
    currentApplicants: 0,
    lastPosted: ['4/12/2023', '2:32:33 AM'],
  },
];
